---

# tasks file for sonar-app
- hosts: [sonar-app]
  become: yes
  become_method: sudo
  handlers:
  vars:
    - include: ../handlers/main.yml
    # get vars
    - include_vars: ../defaults/main.yml
    - include_vars: ../vars/main.yml
  tasks:

    # Install dependencies
    - include: dependencies.yml

    # Install sonar runner
    - include: runner.yml

    # Install sonar plugins
    - include: plugins.yml

    # Run configuration
    - include: config.yml
